import React, { useState, useEffect, useRef } from 'react';
import type { ChatMessage, Planet, SimulationData, ChatTarget } from '../types';
import { startChatSession, continueChat, createImageGenerationPrompt } from '../services/geminiService';
import MarkdownRenderer from './MarkdownRenderer';

interface ChatViewProps {
  planet: Planet;
  simulationData: SimulationData;
  chatTarget: ChatTarget;
  onBack: () => void;
}

const CharacterAvatar: React.FC = () => (
    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-teal-400 to-purple-500 flex items-center justify-center shadow-lg">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-white" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 16a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
        </svg>
    </div>
);

const ChatView: React.FC<ChatViewProps> = ({ planet, simulationData, chatTarget, onBack }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    startChatSession(planet.name, simulationData.cityName, chatTarget);
    const initialMessage = `سلام دوست من! من ${chatTarget.role} تو در شهر ${simulationData.cityName} هستم. هر سوالی داری ازم بپرس! :)`;

    setMessages([
      { role: 'model', text: initialMessage }
    ]);
    // eslint-disable--next-line react-hooks/exhaustive-deps
  }, [planet, simulationData, chatTarget]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(scrollToBottom, [messages]);

  const handleSend = async () => {
    if (input.trim() === '' || isLoading) return;

    const userMessage: ChatMessage = { role: 'user', text: input };
    setMessages(prev => [...prev, userMessage]);
    const currentInput = input;
    setInput('');
    setIsLoading(true);

    try {
      const responseText = await continueChat(currentInput);
      const modelMessage: ChatMessage = { role: 'model', text: responseText };
      setMessages(prev => [...prev, modelMessage]);
    } catch (error) {
      const errorMessage: ChatMessage = { role: 'model', text: 'اوه! مثل اینکه خط‌های ارتباطی ما قطع شده. می‌تونی بعدا دوباره امتحان کنی؟' };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateImage = async () => {
    if (input.trim() === '' || isLoading) return;

    const imageSubject = input;
    const userMessage: ChatMessage = { role: 'user', text: `یک عکس از این بکش: ${imageSubject}` };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    try {
        const prompt = await createImageGenerationPrompt(imageSubject);
        const imageUrl = `https://pollinations.ai/p/${encodeURIComponent(prompt)}`;
        const imageMessage: ChatMessage = { role: 'model', imageUrl: imageUrl };
        setMessages(prev => [...prev, imageMessage]);
    } catch (error) {
        const errorMessage: ChatMessage = { role: 'model', text: 'متاسفانه مداد رنگی‌های من تموم شدن و نمی‌تونم عکس بکشم. بعدا دوباره امتحان کن!' };
        setMessages(prev => [...prev, errorMessage]);
    } finally {
        setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-gray-800 text-white p-4">
      <div className="flex items-center justify-between pb-4 border-b-2 border-gray-700">
        <button onClick={onBack} className="bg-gray-700 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-full transition-colors duration-200">
          &rarr; بازگشت
        </button>
        <div className="text-center">
          <h2 className="text-2xl font-display text-yellow-400">گفتگو با {chatTarget.role}</h2>
          <p className="text-sm text-gray-400">در شهر {simulationData.cityName}</p>
        </div>
        <div className="w-24"></div> {/* Spacer */}
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {messages.map((msg, index) => (
          <div key={index} className={`flex items-end gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            {msg.role === 'model' && <CharacterAvatar />}
            <div className={`max-w-lg p-4 rounded-2xl text-lg ${msg.role === 'user' ? 'bg-blue-600 rounded-br-none' : 'bg-gray-700 rounded-bl-none'}`}>
               {msg.imageUrl ? (
                 <img src={msg.imageUrl} alt="Generated by AI" className="rounded-lg" />
               ) : msg.role === 'model' && msg.text ? (
                 <MarkdownRenderer text={msg.text} />
               ) : (
                 <p>{msg.text}</p>
               )}
            </div>
          </div>
        ))}
        {isLoading && (
          <div className="flex items-end gap-3 justify-start">
             <CharacterAvatar />
            <div className="max-w-lg p-4 rounded-2xl bg-gray-700 rounded-bl-none">
              <div className="flex items-center space-x-2 space-x-reverse">
                <div className="w-3 h-3 bg-gray-300 rounded-full animate-bounce"></div>
                <div className="w-3 h-3 bg-gray-300 rounded-full animate-bounce delay-150"></div>
                <div className="w-3 h-3 bg-gray-300 rounded-full animate-bounce delay-300"></div>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="mt-auto p-2 border-t-2 border-gray-700">
        <div className="flex items-center bg-gray-900 rounded-full p-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && handleSend()}
            placeholder="یک سوال بپرس..."
            className="flex-1 bg-transparent text-white placeholder-gray-400 focus:outline-none px-4"
            disabled={isLoading}
          />
          <button
            onClick={handleGenerateImage}
            disabled={isLoading || input.trim() === ''}
            className="text-white rounded-full p-3 hover:bg-yellow-500 disabled:text-gray-500 disabled:cursor-not-allowed transition-colors"
            title="برام نقاشی بکش"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
            </svg>
          </button>
          <button
            onClick={handleSend}
            disabled={isLoading || input.trim() === ''}
            className="bg-teal-500 text-white rounded-full p-3 hover:bg-teal-600 disabled:bg-gray-600 disabled:cursor-not-allowed transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 transform -rotate-90" fill="none" viewBox="ool 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
};

export default ChatView;